project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Project description"
        contents:
          - about.qmd
      - section: "Analyses"
        contents:
          - text: "1. sample information"
            file: sample_bio.qmd
          - text: "2. visualization customs"
            file: customs.qmd
          - text: "3. proficiency"
            file: proficiency.qmd
          - text: "4. naming and feedback"
            file: feedbacks.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

