project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Project description"
        contents:
          - about.qmd
      - section: "Analyses"
        contents:
          - text: "1. sample bio"
            file: sample_bio.qmd
          - text: "2. visualisation customs"
            file: exploration.qmd
          - text: "3. linear models"
            file: connections.qmd
          - text: "4. plot breakdown"
            file: plot_breakdown.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

