---
title: "Proficiency"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
    code-fold: true
    code-summary: "Show the code"
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## Setup

```{r, message= FALSE, warning=FALSE, echo=FALSE}
library(readxl)
library(foreach)
library(stringr)
library(dplyr)
library(tokenizers)
library(data.table)
library(ggplot2)
library(plyr)
library(quanteda)
library(purrr)
library(tidytext)
library(tm)
library(SnowballC)
library(Matrix)
library(text2vec)
library(tidyr)
library(janitor)
library(GGally)
library(formattable)
library(kableExtra)
library(FactoMineR)
library(psych)
library(factoextra)
```

```{r, message= FALSE, warning=FALSE}
data <- read_excel("data/results-survey.xlsx")
data <- data[1:121] %>% 
  filter(.[[18]] !='Yes', .[[20]] < 80) # not analysed any EEG method
```

## Proficiency factor

```{r, include=FALSE}
exp_data <- data[c( 19, 20, 12, 21, 22)]
colnames(exp_data) <- c("n_papers", "years", "position","self_level", "code_contribution")
exp_data


short <- exp_data[c(1:2, 5)] %>% mutate(code_contribution = ifelse(code_contribution=="Yes", 1, 0))

```

```{r}
m = FAMD(exp_data[1:5], ncp=2, axes=c(1,2))

# pics <- fviz_famd_ind(m, col.ind = "cos2", 
#              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
#              repel = TRUE)

```

### test

Proxy Proficiency should definitely correlate with years of experience

```{r}
factor_scores <- as.data.frame(m$ind$coord)
head(factor_scores)

cbind(data[20], factor_scores[1])  %>% 
   rename_at(vars(colnames(.)), ~ c("years", "proxy")) %>% 
  with(cor.test( proxy, years)) %>% 
  broom::tidy() %>% dplyr::select(estimate, p.value)
```

## Tiles
### t.tests

```{r}
fun <- function(df) t.test(df$proxy ~ df$score) 

cbind(factor_scores[1], data[79]) %>% cbind(., data[117]) %>% 
  cbind(., data[118]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "ud", "jet_aware", "twod_aware")) %>%
  mutate(ud = ifelse(ud=="Up", 1, 0), 
         jet_aware = ifelse(jet_aware =="Yes", 1, 0),
         twod_aware = ifelse(twod_aware =="Yes", 1, 0)) %>% 
  gather(type, score, ud:twod_aware) %>% 
  dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, fun)) %>% unnest() %>% 
  dplyr::select(type, estimate, p.value, method) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")


```

```{r}
vec <- names(data[25:51]) %>% str_split_i(., "\\? \\[", 2) %>%  str_sub(., 1, -2)

data[25:51] %>%
  rename_at(vars(colnames(.)), ~ vec) %>% 
  dplyr::select(-Other) %>% 
  mutate_at(vars(vec[1:26]), function(., na.rm = FALSE) (x = ifelse(.=="Yes", 1, 0))) %>% select_if(colSums(.) > 10) %>% 
  cbind(factor_scores[1], .) %>% dplyr::rename(proxy = !!names(.)[1]) %>% 
  gather(type, score, BESA:`Custom scripts`) %>% 
   dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, fun)) %>% unnest() %>% 
  dplyr::select(type, estimate, p.value, method) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")
  

```

### cor.tests

```{r}
vec <- names(data[25:50]) %>% str_split_i(., "\\? \\[", 2) %>%  str_sub(., 1, -2)

cor_fun <- function(df) cor.test(df$proxy, df$score, method = "spearman") %>% tidy()

n_soft <- data[25:50] %>%
  rename_at(vars(colnames(.)), ~ vec) %>% 
  mutate_at(vars(vec), function(., na.rm = FALSE) (x = ifelse(.=="Yes", 1, 0)))%>%
  rowSums() %>% tibble()

cbind(factor_scores[1], data[23]) %>% cbind(., data[24]) %>%  cbind(., n_soft) %>%
  rename_at(vars(colnames(.)), ~ c("proxy", "measure", "analyse", "n_soft")) %>%
  dplyr::filter(analyse < 500) %>% tibble() %>% 
  mutate(rate = analyse / measure) %>% 
  dplyr::select(-analyse, -measure) %>% 
  gather(type, score, rate:n_soft) %>% 
  dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, cor_fun)) %>% unnest() %>% 
  dplyr::select(type, estimate, p.value, method) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")


```
```{r}
feature <- data[52:60] %>% rename_all(., ~str_split_i(colnames(data[52:60]), "\\? \\[", 2) %>% str_sub(., 1, -2) ) %>%  
  mutate_at(c(colnames(.)), 
        funs(recode(.,
        "Very important"= 2, "Important"= 1, "Neutral"= 0,
        "Low importance"= -1, "Not at all important" = -2 )))  %>% 
  cbind(., factor_scores[1]) %>%  
  rename_at(vars(colnames(.)), ~ c("subplot", "attributes", "speed", "publicable", "reproducable", "zooming", "interactive", "gui", "coding", "proxy")) 

feature %>% 
  gather(type, score, subplot:coding) %>% 
  dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, cor_fun)) %>% unnest() %>% 
  dplyr::select(type, estimate, p.value, method) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")

```

### log reg

```{r}
log_fun <- function(df) glm(df$score ~ df$proxy, family = "binomial") %>% tidy() %>% slice(-1)

cbind(factor_scores[1], data[79]) %>% cbind(., data[117]) %>% 
  cbind(., data[118]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "ud", "jet_aware", "twod_aware")) %>%
  mutate(ud = ifelse(ud=="Up", 1, 0), 
         jet_aware = ifelse(jet_aware =="Yes", 1, 0),
         twod_aware = ifelse(twod_aware =="Yes", 1, 0)) %>% 
  gather(type, score, ud:twod_aware) %>% 
  dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, log_fun)) %>% unnest() %>% 
  dplyr::select(type, term, estimate, std.error, p.value) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")
```
```{r}
vec <- names(data[25:51]) %>% str_split_i(., "\\? \\[", 2) %>%  str_sub(., 1, -2)

data[25:51] %>%
  rename_at(vars(colnames(.)), ~ vec) %>% 
  dplyr::select(-Other) %>% 
  mutate_at(vars(vec[1:26]), function(., na.rm = FALSE) (x = ifelse(.=="Yes", 1, 0))) %>% select_if(colSums(.) > 10) %>% 
  cbind(factor_scores[1], .) %>% dplyr::rename(proxy = !!names(.)[1]) %>% 
  gather(type, score, BESA:`Custom scripts`) %>% 
   dplyr::group_by(., type) %>% nest() %>% 
  dplyr::mutate(., model = map(data, log_fun)) %>% unnest() %>% 
  dplyr::select(type, term, estimate, std.error, p.value) %>%
  dplyr::group_by(type) %>%  slice(1) %>% mutate(p.value = round(as.numeric(p.value), 3)) %>%
  mutate(p.value = cell_spec(p.value, color = ifelse(p.value < 0.05, "green", "black"))) %>% 
  kable(escape = F, booktabs = T) %>% 
  kable_classic(full_width = T, html_font = "Arial")
```


## Proficiency and ...

### Tools

```{r}
cbind(factor_scores[1], data[31]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "EEGLAB")) %>%
  mutate(EEGLAB = ifelse(EEGLAB =="Yes", 1, 0)) %>% 
  ggplot(., aes(x=as.factor(EEGLAB), y = proxy)) + 
  geom_boxplot() + labs(x = "EEGLAB", y = "Experience") +  
  theme_classic()

cbind(factor_scores[1], data[35]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "ERPLAB")) %>%
  mutate(ERPLAB = ifelse(ERPLAB =="Yes", 1, 0)) %>% 
  ggplot(., aes(x=as.factor(ERPLAB), y = proxy)) + 
  geom_boxplot() + labs(x = "ERPLAB", y = "Experience") +  
  theme_classic()

cbind(factor_scores[1], data[41]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "Fieldtrip")) %>%
  mutate(Fieldtrip = ifelse(Fieldtrip =="Yes", 1, 0)) %>% 
  ggplot(., aes(x=as.factor(Fieldtrip), y = proxy)) + 
  geom_boxplot() + labs(x = "Fieldtrip", y = "Experience") +  
  theme_classic()

cbind(factor_scores[1], data[43]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "LIMO")) %>%
  mutate(LIMO = ifelse(LIMO =="Yes", 1, 0)) %>% 
  ggplot(., aes(x=as.factor(LIMO), y = proxy)) + 
  geom_boxplot() + labs(x = "LIMO", y = "Experience") +  
  theme_classic()
```

### Number of used software

```{r}
vec <- names(data[25:50]) %>% str_split_i(., "\\? \\[", 2) %>%  str_sub(., 1, -2)

software <- data[25:50] %>%
    rename_at(vars(colnames(.)), ~ vec) %>% 
  mutate_at(vars(vec), function(., na.rm = FALSE) (x = ifelse(.=="Yes", 1, 0))) %>% rowSums() %>% tibble()

```

```{r}
cbind(data.frame(rowSums(software)), factor_scores[1])  %>% 
   rename_at(vars(colnames(.)), ~ c("n_soft", "experience")) %>% 
  filter(n_soft > 0) %>% 
  ggplot(., aes(x=n_soft, y=experience)) + geom_jitter() + geom_smooth()
```

```{r}
cbind(data.frame(rowSums(software)), factor_scores[1])  %>% 
   rename_at(vars(colnames(.)), ~ c("n_soft", "experience")) %>% 
  filter(n_soft > 0) %>% 
  lm(data=., n_soft ~ experience) %>% summary(.)
```

### Features

```{r}
feature <- data[52:60] %>% rename_all(., ~str_split_i(colnames(data[52:60]), "\\? \\[", 2) %>% str_sub(., 1, -2) ) %>%  
  mutate_at(c(colnames(.)), 
        funs(recode(.,
        "Very important"= 2, "Important"= 1, "Neutral"= 0,
        "Low importance"= -1, "Not at all important" = -2 )))  %>% 
  cbind(., factor_scores[1]) %>%  
  rename_at(vars(colnames(.)), ~ c("subplot", "attributes", "speed", "publicable", "reproducable", "zooming", "interactive", "gui", "coding", "experience")) 
```


```{r}
filter_all(all_vars(!is.na(.))) %>%  
  rename_at(vars(colnames(.)), ~ c("subplot", "attributes", "speed", "publicable", "reproducable", "zooming", "interactive", "gui", "coding", "experience")) %>% 
  mutate(experience = round(experience, 2), exp_cut = cut(experience, 4, labels = c("25%", "50%", "75%", "100%")), 
         exp_quant = factor(ntile(experience, 4))) %>% 
  group_by(exp_quant) %>% dplyr::mutate(n = n()) %>% ungroup() 
```

```{r}
table(feature$exp_quant)
```

```{r}
feature %>% 
  pivot_longer(cols = subplot:coding, names_to = "feature", values_to = "likert") %>% 
  mutate(likert = likert + 3) %>% 
  group_by(feature, exp_quant) %>% dplyr::summarise(m = mean(likert)) %>% 
  ggplot(aes(y = m, x= exp_quant, fill = exp_quant)) + 
  geom_bar(stat = "identity") + 
  #geom_smooth(aes(y = value, x= experience, color = str_wrap(name, 20)), bw = 0.5, method = "loess", span = 0.7) + 
  labs(y = "Mean likert scale value", x="Experience quartiles", color = "Features")  + theme_classic() +
  theme(legend.position = "none", 
        legend.key.height=unit(2, "cm"), 
        axis.text.x = element_text(size = 12),
        strip.text = element_text(size = 14)) + 
  facet_wrap(~str_wrap(feature, 20)) + 
  geom_text(aes(label = paste0(round(m, 1))),  position = position_stack(vjust = 0.5), size = 4) 

```

```{r}
feature %>% 
  pivot_longer(cols = subplot:coding, names_to = "feature", values_to = "likert") %>%
  mutate(likert = likert + 3) %>%
  ggplot(aes(x = likert, fill= experience, colour = exp_quant)) + 
  geom_density(key_glyph = "timeseries", bw = 0.5) +
  labs(x = "Mean likert scale value", y="Experience quartiles", color = "Experience\nquantiles")  + 
  theme_classic() + scale_colour_brewer(palette = "Spectral") +
  theme(legend.position = "right", 
        #legend.key.height=unit(2, "cm"), 
        axis.text.x = element_text(size = 12),
        strip.text = element_text(size = 14)) + 
  facet_wrap(~str_wrap(feature, 20)) 
```

### Channels

```{r}
data %>% select(23, 24) %>% 
  cbind(., factor_scores[1]) %>% 
  rename_at(vars(colnames(.)), ~ c("measure", "analyse", "experience")) %>% 
  filter(analyse < 500) %>% 
  mutate(rate = analyse / measure) %>% 
  ggplot(., aes(x=rate, y=experience)) + 
  geom_point() +                                      
  stat_smooth(method = "lm",
              formula = y ~ x,
              geom = "smooth") +
  labs(x ="analyse / measure") +
  theme_classic()
```
```{r}
data %>% select(23, 24) %>% 
  cbind(., factor_scores[1]) %>% 
  rename_at(vars(colnames(.)), ~ c("measure", "analyse", "experience")) %>% 
  filter(analyse < 500) %>% 
  mutate(rate = analyse / measure) %>%
  lm(rate ~ experience, .) %>% summary()
```
### n_plot

```{r}
n_soft <- data[25:50] %>%
    rename_at(vars(colnames(.)), ~ vec) %>% 
  mutate_at(vars(vec), function(., na.rm = FALSE) (x = ifelse(.=="Yes", 1, 0))) %>% rowSums() %>% tibble()

cbind(n_soft, factor_scores[1]) %>% 
  rename_at(vars(colnames(.)), ~ c("n_soft", "experience")) %>% 
  ggplot(., aes(x=n_soft, y=experience)) + 
  geom_point() +                                      
  stat_smooth(method = "lm",
              formula = y ~ x,
              geom = "smooth") +
  labs(x ="n_soft") +
  theme_classic()
```
### jet awareness

```{r}
cbind(factor_scores[1], data[117]) %>% 
  rename_at(vars(colnames(.)), ~ c("proxy", "jet_aware")) %>%
  mutate(jet_aware = ifelse(jet_aware =="Yes", 1, 0)) %>% 
  ggplot(., aes(x=as.factor(jet_aware), y = proxy)) + 
  geom_boxplot() + labs(x = "Aware or not abour colorbar controvercies", y = "Experience") +  
  theme_classic()
```